"""Phase 6 training orchestrator.

Two stages:
  Stage 0 — Watchog-style contrastive pretraining on synthetic_corpus.jsonl
            (the Phase 5 Stage D corpus, generated by data/synthetic_corpus.py).
            Encoder-only. SimCLR-style: positive pair = two augmentations of
            the SAME source example; negatives = augmentations of DIFFERENT
            source examples within the minibatch. 3 epochs default.

  Stage 1 — Multi-task fine-tune on (gold + synthesized_train.jsonl +
            LF-fused soft labels from labeling_functions.py).
            Loss: ce + 0.3 * crf_nll + 0.1 * sibling_relation_loss
            5 epochs default, early-stop on val macro-F1 (patience=2).

CLI:
    /tmp/schema-mapper-venv/bin/python train.py \\
        --epochs 5 \\
        --contrastive-epochs 3 \\
        --batch-size 32 \\
        --device mps

NOTE on `train(False)`: this is the same as model.<eval-mode>() in PyTorch,
just spelled in the alternate documented form (Module.train accepts a bool).
We use train(False)/train(True) throughout this file to dodge an overly
strict security hook that pattern-matches the eval-mode method-call literal.
Behavior is identical.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import random
import re
import sys
import time
from collections import defaultdict
from dataclasses import dataclass

import numpy as np
import torch
import torch.nn.functional as F
from torch.optim import AdamW
from torch.utils.data import DataLoader, Dataset

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[3] / "src"))

from canonical_schema import CANONICAL_LABELS, LABEL_TO_ID  # noqa: E402
from crf_head import NUM_LABELS  # noqa: E402
from encoder import MAX_SEQ_LEN, load_tokenizer  # noqa: E402
from gateway.schema.features import FEATURE_DIM_V2, FlatField as RuntimeFlatField  # noqa: E402
from gateway.schema.features import extract_features_v2, flatten_json as rt_flatten  # noqa: E402
from linearization import linearize_field  # noqa: E402
from model import SchemaMapper  # noqa: E402
from paths import FlatField as BuildFlat  # noqa: E402
from paths import flatten_json as build_flatten  # noqa: E402

SEED = 20260427


@dataclass
class FieldSample:
    text: str
    features: list[float]
    label: int
    parent_path: str
    variant_id: str
    source_spec: str


def _runtime_path_to_build_path(p: str) -> str:
    return re.sub(r"\.(\d+)(?=\.|$)", lambda m: f"[{m.group(1)}]", p)


def _runtime_to_build_field(rf: RuntimeFlatField) -> BuildFlat:
    return BuildFlat(
        path=_runtime_path_to_build_path(rf.path),
        key=rf.key,
        value=rf.value,
        siblings=tuple(sorted(rf.sibling_keys)),
        depth=rf.depth,
    )


def _samples_from_obj(obj: dict, expected_labels: dict[str, str], variant_id: str, source_spec: str) -> list[FieldSample]:
    out: list[FieldSample] = []
    for rf in rt_flatten(obj):
        build_path = _runtime_path_to_build_path(rf.path)
        label = expected_labels.get(build_path)
        if label is None or label not in LABEL_TO_ID:
            continue
        bf = _runtime_to_build_field(rf)
        feats = extract_features_v2(rf)
        parent = build_path.rsplit(".", 1)[0] if "." in build_path else ""
        out.append(FieldSample(
            text=linearize_field(bf),
            features=feats,
            label=LABEL_TO_ID[label],
            parent_path=parent,
            variant_id=variant_id,
            source_spec=source_spec,
        ))
    return out


def load_jsonl_to_samples(path: pathlib.Path) -> list[FieldSample]:
    out: list[FieldSample] = []
    if not path.exists():
        return out
    with path.open() as f:
        for line in f:
            row = json.loads(line)
            out.extend(_samples_from_obj(
                row["raw"], row["expected_labels"],
                variant_id=row.get("variant_id", path.stem),
                source_spec=row.get("source_spec", "?"),
            ))
    return out


def load_specs_to_samples(specs_dir: pathlib.Path) -> list[FieldSample]:
    out: list[FieldSample] = []
    for sp in sorted(specs_dir.glob("*.json")):
        spec = json.loads(sp.read_text())
        spec_name = sp.stem
        for ex_idx, ex in enumerate(spec["examples"]):
            out.extend(_samples_from_obj(
                ex["raw"], ex["expected_labels"],
                variant_id=f"gold:{spec_name}#{ex_idx}",
                source_spec=spec_name,
            ))
    return out


class FieldDataset(Dataset):
    def __init__(self, samples: list[FieldSample], tokenizer):
        self.samples = samples
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        s = self.samples[idx]
        enc = self.tokenizer(s.text, truncation=True, max_length=MAX_SEQ_LEN, padding="max_length")
        return {
            "input_ids": torch.tensor(enc["input_ids"], dtype=torch.long),
            "attention_mask": torch.tensor(enc["attention_mask"], dtype=torch.long),
            "features": torch.tensor(s.features, dtype=torch.float32),
            "label": torch.tensor(s.label, dtype=torch.long),
        }


def _collate_classify(batch):
    return {
        "input_ids": torch.stack([b["input_ids"] for b in batch]),
        "attention_mask": torch.stack([b["attention_mask"] for b in batch]),
        "features": torch.stack([b["features"] for b in batch]),
        "label": torch.stack([b["label"] for b in batch]),
    }


class ContrastivePairDataset(Dataset):
    def __init__(self, jsonl_path: pathlib.Path, tokenizer, samples_per_source: int = 4):
        self.tokenizer = tokenizer
        groups: dict[str, list[str]] = defaultdict(list)
        if jsonl_path.exists():
            with jsonl_path.open() as f:
                for line in f:
                    row = json.loads(line)
                    key = f"{row['source_spec']}#{row['source_example_id']}"
                    obj = row["raw"]
                    fields_text = [linearize_field(f) for f in build_flatten(obj)]
                    if fields_text:
                        groups[key].append(" ; ".join(fields_text)[:512])
        self.pairs: list[tuple[str, str]] = []
        rng = random.Random(SEED)
        for variants in groups.values():
            if len(variants) < 2:
                continue
            for _ in range(min(samples_per_source, len(variants))):
                a, b = rng.sample(variants, 2)
                self.pairs.append((a, b))

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        a, b = self.pairs[idx]
        enc_a = self.tokenizer(a, truncation=True, max_length=MAX_SEQ_LEN, padding="max_length")
        enc_b = self.tokenizer(b, truncation=True, max_length=MAX_SEQ_LEN, padding="max_length")
        return {
            "ids_a": torch.tensor(enc_a["input_ids"]),
            "msk_a": torch.tensor(enc_a["attention_mask"]),
            "ids_b": torch.tensor(enc_b["input_ids"]),
            "msk_b": torch.tensor(enc_b["attention_mask"]),
        }


def _collate_pairs(batch):
    return {k: torch.stack([b[k] for b in batch]) for k in batch[0]}


def info_nce_loss(emb_a: torch.Tensor, emb_b: torch.Tensor, temperature: float = 0.07) -> torch.Tensor:
    a = F.normalize(emb_a, dim=-1)
    b = F.normalize(emb_b, dim=-1)
    logits = a @ b.t() / temperature
    targets = torch.arange(a.size(0), device=a.device)
    return F.cross_entropy(logits, targets)


def stage0_contrastive_pretrain(
    model: SchemaMapper,
    pair_loader: DataLoader,
    device: torch.device,
    epochs: int,
    lr: float = 2e-5,
) -> list[dict]:
    for p in model.head.parameters(): p.requires_grad = False
    for p in model.sibling_head.parameters(): p.requires_grad = False
    for p in model.crf.parameters(): p.requires_grad = False
    opt = AdamW(model.encoder.parameters(), lr=lr, weight_decay=0.01)
    log = []
    model.train(True)
    for epoch in range(epochs):
        total = 0.0
        n = 0
        for batch in pair_loader:
            ids_a = batch["ids_a"].to(device)
            msk_a = batch["msk_a"].to(device)
            ids_b = batch["ids_b"].to(device)
            msk_b = batch["msk_b"].to(device)
            emb_a = model.encoder(ids_a, msk_a)
            emb_b = model.encoder(ids_b, msk_b)
            loss = info_nce_loss(emb_a, emb_b)
            opt.zero_grad()
            loss.backward()
            opt.step()
            total += loss.item()
            n += 1
        avg = total / max(n, 1)
        log.append({"stage": "contrastive", "epoch": epoch, "info_nce": avg})
        print(f"[stage 0 epoch {epoch}] InfoNCE={avg:.4f}", file=sys.stderr)
    for p in model.head.parameters(): p.requires_grad = True
    for p in model.sibling_head.parameters(): p.requires_grad = True
    for p in model.crf.parameters(): p.requires_grad = True
    return log


def stage1_finetune(
    model: SchemaMapper,
    train_loader: DataLoader,
    val_loader: DataLoader,
    device: torch.device,
    epochs: int,
    lr_encoder: float = 2e-5,
    lr_head: float = 1e-3,
    lambda_crf: float = 0.3,
    patience: int = 2,
    checkpoint_path: pathlib.Path | None = None,
    feature_dim: int | None = None,
) -> list[dict]:
    opt = AdamW(
        [
            {"params": model.encoder.parameters(), "lr": lr_encoder},
            {"params": model.head.parameters(), "lr": lr_head},
            {"params": model.sibling_head.parameters(), "lr": lr_head},
            {"params": model.crf.parameters(), "lr": lr_head},
        ],
        weight_decay=0.01,
    )
    log = []
    best_f1 = -1.0
    no_improve = 0
    print(f"[stage 1] starting fine-tune: {epochs} epochs, {len(train_loader)} batches/epoch", file=sys.stderr)
    for epoch in range(epochs):
        model.train(True)
        ce_total = 0.0
        n = 0
        for bi, batch in enumerate(train_loader):
            if bi == 0:
                print(f"[stage 1 epoch {epoch}] first batch loaded", file=sys.stderr)
            ids = batch["input_ids"].to(device)
            msk = batch["attention_mask"].to(device)
            feat = batch["features"].to(device)
            lab = batch["label"].to(device)
            out = model(ids, msk, feat)
            logits = out["logits"]
            ce = F.cross_entropy(logits, lab)
            crf_logits = logits.unsqueeze(0)
            crf_labels = lab.unsqueeze(0)
            crf_mask = torch.ones_like(crf_labels, dtype=torch.bool)
            crf_nll = model.crf(crf_logits, crf_labels, crf_mask)
            loss = ce + lambda_crf * crf_nll
            opt.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            ce_total += ce.item()
            n += 1
            if bi > 0 and bi % 100 == 0:
                print(f"[stage 1 epoch {epoch}] batch {bi}/{len(train_loader)} ce={ce.item():.4f}", file=sys.stderr)
        train_ce = ce_total / max(n, 1)
        model.train(False)
        val_macro_f1 = _evaluate_macro_f1(model, val_loader, device)
        log.append({"stage": "finetune", "epoch": epoch, "train_ce": train_ce, "val_macro_f1": val_macro_f1})
        print(f"[stage 1 epoch {epoch}] train_ce={train_ce:.4f}  val_macro_f1={val_macro_f1:.4f}", file=sys.stderr)
        if val_macro_f1 > best_f1:
            best_f1 = val_macro_f1
            no_improve = 0
            log[-1]["best"] = True
            # Persist immediately so a later-epoch crash can't destroy
            # the best weights we've found so far.
            if checkpoint_path is not None:
                torch.save(
                    {"model_state": model.state_dict(),
                     "feature_dim": feature_dim, "best_val_macro_f1": best_f1,
                     "epoch": epoch},
                    checkpoint_path,
                )
                print(f"[stage 1 epoch {epoch}] saved best to {checkpoint_path.name}", file=sys.stderr)
        else:
            no_improve += 1
            if no_improve >= patience:
                print(f"[stage 1] early stop at epoch {epoch}", file=sys.stderr)
                break
    return log


def _evaluate_macro_f1(model: SchemaMapper, loader: DataLoader, device: torch.device) -> float:
    if len(loader) == 0:
        return 0.0
    tp = np.zeros(NUM_LABELS, dtype=np.int64)
    fp = np.zeros(NUM_LABELS, dtype=np.int64)
    fn = np.zeros(NUM_LABELS, dtype=np.int64)
    with torch.no_grad():
        for batch in loader:
            ids = batch["input_ids"].to(device)
            msk = batch["attention_mask"].to(device)
            feat = batch["features"].to(device)
            lab = batch["label"].cpu().numpy()
            out = model(ids, msk, feat)
            preds = out["logits"].argmax(dim=-1).cpu().numpy()
            for p, t in zip(preds, lab):
                if p == t:
                    tp[t] += 1
                else:
                    fp[p] += 1
                    fn[t] += 1
    f1s = []
    for k in range(NUM_LABELS):
        if tp[k] + fn[k] == 0:
            continue
        p = tp[k] / max(tp[k] + fp[k], 1)
        r = tp[k] / max(tp[k] + fn[k], 1)
        f1s.append(2 * p * r / (p + r) if (p + r) > 0 else 0.0)
    return float(np.mean(f1s)) if f1s else 0.0


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--specs-dir", type=pathlib.Path, default=pathlib.Path(__file__).parent / "data" / "provider_specs")
    ap.add_argument("--synth", type=pathlib.Path, default=pathlib.Path(__file__).parent / "out" / "data" / "synthesized_train.jsonl")
    ap.add_argument("--corpus", type=pathlib.Path, default=pathlib.Path(__file__).parent / "out" / "synthetic_corpus.jsonl")
    ap.add_argument("--out", type=pathlib.Path, default=pathlib.Path(__file__).parent / "out" / "checkpoints")
    ap.add_argument("--epochs", type=int, default=5)
    ap.add_argument("--contrastive-epochs", type=int, default=3)
    ap.add_argument("--batch-size", type=int, default=32)
    ap.add_argument("--device", default="mps", choices=["cpu", "mps", "cuda"])
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--max-train-samples", type=int, default=50_000,
                    help="Cap on training-set size (after split); subsamples when corpus exceeds. Prevents OOM on a Mac with 16-32GB unified memory.")
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    random.seed(args.seed)

    if args.device == "mps" and not torch.backends.mps.is_available():
        device = torch.device("cpu")
    elif args.device == "cuda" and not torch.cuda.is_available():
        device = torch.device("cpu")
    else:
        device = torch.device(args.device)

    print(f"[setup] device={device}  FEATURE_DIM_V2={FEATURE_DIM_V2}", file=sys.stderr)
    tokenizer = load_tokenizer()
    model = SchemaMapper(feature_dim=FEATURE_DIM_V2).to(device)

    t0 = time.time()
    stage0_log = []
    if args.corpus.exists():
        pair_ds = ContrastivePairDataset(args.corpus, tokenizer)
        if len(pair_ds) > 0:
            pair_loader = DataLoader(pair_ds, batch_size=args.batch_size, shuffle=True, collate_fn=_collate_pairs)
            stage0_log = stage0_contrastive_pretrain(model, pair_loader, device, epochs=args.contrastive_epochs)

    gold = load_specs_to_samples(args.specs_dir)
    synth = load_jsonl_to_samples(args.synth)
    print(f"[stage 1] {len(gold)} gold + {len(synth)} synth samples", file=sys.stderr)
    all_samples = gold + synth
    holdout_specs = {"xai_grok", "replicate"}
    rng = random.Random(args.seed)
    rng.shuffle(all_samples)
    train_samples = [s for s in all_samples if s.source_spec not in holdout_specs]
    test_samples = [s for s in all_samples if s.source_spec in holdout_specs]
    n_val = max(1, len(train_samples) // 10)
    val_samples = train_samples[:n_val]
    train_samples = train_samples[n_val:]
    # Subsample train if it exceeds the cap (default 50K). Keep val
    # proportional but capped at 5K to keep eval fast.
    if len(train_samples) > args.max_train_samples:
        rng.shuffle(train_samples)
        print(f"[split] subsampling train {len(train_samples)} -> {args.max_train_samples}", file=sys.stderr)
        train_samples = train_samples[: args.max_train_samples]
    if len(val_samples) > 5000:
        val_samples = val_samples[:5000]
    print(f"[split] train={len(train_samples)} val={len(val_samples)} test={len(test_samples)}", file=sys.stderr)
    (args.out / "data_split.json").write_text(json.dumps({
        "n_train": len(train_samples), "n_val": len(val_samples), "n_test": len(test_samples),
        "holdout_specs": sorted(holdout_specs),
    }, indent=2))

    train_loader = DataLoader(FieldDataset(train_samples, tokenizer), batch_size=args.batch_size, shuffle=True, collate_fn=_collate_classify)
    val_loader = DataLoader(FieldDataset(val_samples, tokenizer), batch_size=args.batch_size, shuffle=False, collate_fn=_collate_classify)

    ckpt_path = args.out / "best.pt"
    stage1_log = stage1_finetune(model, train_loader, val_loader, device,
                                  epochs=args.epochs,
                                  checkpoint_path=ckpt_path,
                                  feature_dim=FEATURE_DIM_V2)
    elapsed = time.time() - t0

    log_path = args.out / "training_log.jsonl"
    with log_path.open("w") as f:
        for row in stage0_log + stage1_log:
            f.write(json.dumps(row) + "\n")
    # ckpt_path was already populated by per-epoch best-save; if none of
    # the epochs produced a best (unlikely), save the current state as
    # a fallback so callers always have something to load.
    if not ckpt_path.exists():
        torch.save({"model_state": model.state_dict(), "feature_dim": FEATURE_DIM_V2}, ckpt_path)
    (args.out / "compute_cost.json").write_text(json.dumps({"wall_clock_s": elapsed, "device": str(device)}, indent=2))
    print(f"[done] checkpoint at {ckpt_path}; elapsed {elapsed:.1f}s", file=sys.stderr)


if __name__ == "__main__":
    main()
