// Walacor Gateway — gRPC interface between Go proxy and Python governance sidecar.
//
// The Go proxy handles HTTP ingress, TLS, connection pooling, and LLM provider
// forwarding.  All governance intelligence (policy evaluation, content analysis,
// session chains, audit hashing, tool execution, caching) lives in the Python
// sidecar and is accessed via this service.
//
// Wire format: proto3.  Transport: gRPC over Unix domain socket (default) or TCP.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: governance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request payload for EvaluatePreInference.
type PreInferenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller authentication token (API key or JWT).
	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Target model identifier (e.g. "gpt-4o", "qwen3:4b").
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Resolved provider name (e.g. "openai", "ollama", "anthropic").
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// Full prompt text extracted from the request body.
	PromptText string `protobuf:"bytes,4,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	// Tenant identifier for multi-tenant budget/policy scoping.
	TenantId string `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Caller user identifier (from header, JWT, or API key mapping).
	UserId string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Arbitrary key-value metadata from the request (headers, tags, etc.).
	Metadata map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tool definitions available for this request (OpenAI function-calling format).
	Tools []*ToolDefinition `protobuf:"bytes,8,rep,name=tools,proto3" json:"tools,omitempty"`
	// Request classification for system-task detection (e.g. "synthetic", "batch").
	RequestType string `protobuf:"bytes,9,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	// Serialized A/B test configuration JSON (opaque to Go proxy).
	AbTestsJson string `protobuf:"bytes,10,opt,name=ab_tests_json,json=abTestsJson,proto3" json:"ab_tests_json,omitempty"`
	// Session identifier for chain continuity.
	SessionId     string `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreInferenceRequest) Reset() {
	*x = PreInferenceRequest{}
	mi := &file_governance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreInferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreInferenceRequest) ProtoMessage() {}

func (x *PreInferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreInferenceRequest.ProtoReflect.Descriptor instead.
func (*PreInferenceRequest) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{0}
}

func (x *PreInferenceRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *PreInferenceRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PreInferenceRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PreInferenceRequest) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

func (x *PreInferenceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PreInferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PreInferenceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PreInferenceRequest) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *PreInferenceRequest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *PreInferenceRequest) GetAbTestsJson() string {
	if x != nil {
		return x.AbTestsJson
	}
	return ""
}

func (x *PreInferenceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Result from EvaluatePreInference.
type PreInferenceResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the request is allowed to proceed to the LLM provider.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Attestation ID for the model (e.g. "self-attested:qwen3:4b" or a control-plane UUID).
	AttestationId string `protobuf:"bytes,2,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	// Pre-inference policy evaluation result ("pass", "deny", "warn").
	PolicyResult string `protobuf:"bytes,3,opt,name=policy_result,json=policyResult,proto3" json:"policy_result,omitempty"`
	// Policy version that was evaluated.
	PolicyVersion int32 `protobuf:"varint,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Remaining token budget after reservation (absent if budgets not configured).
	BudgetRemaining *int64 `protobuf:"varint,5,opt,name=budget_remaining,json=budgetRemaining,proto3,oneof" json:"budget_remaining,omitempty"`
	// Tool strategy determined by pre-checks ("active", "passive", "none").
	ToolStrategy string `protobuf:"bytes,6,opt,name=tool_strategy,json=toolStrategy,proto3" json:"tool_strategy,omitempty"`
	// Human-readable denial reason (set only when allowed=false).
	DenialReason string `protobuf:"bytes,7,opt,name=denial_reason,json=denialReason,proto3" json:"denial_reason,omitempty"`
	// HTTP status code to return on denial (e.g. 403, 429).
	DenialStatusCode int32 `protobuf:"varint,8,opt,name=denial_status_code,json=denialStatusCode,proto3" json:"denial_status_code,omitempty"`
	// PII-sanitized prompt text (set only when PII sanitization is active).
	SanitizedPrompt *string `protobuf:"bytes,9,opt,name=sanitized_prompt,json=sanitizedPrompt,proto3,oneof" json:"sanitized_prompt,omitempty"`
	// PII token-to-original mapping for post-inference restoration (JSON-encoded).
	PiiMapping string `protobuf:"bytes,10,opt,name=pii_mapping,json=piiMapping,proto3" json:"pii_mapping,omitempty"`
	// Model ID after A/B test rewrite (may differ from the requested model_id).
	ModelId string `protobuf:"bytes,11,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Tools to inject into the LLM request (after capability filtering).
	ResolvedTools []*ToolDefinition `protobuf:"bytes,12,rep,name=resolved_tools,json=resolvedTools,proto3" json:"resolved_tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreInferenceResult) Reset() {
	*x = PreInferenceResult{}
	mi := &file_governance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreInferenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreInferenceResult) ProtoMessage() {}

func (x *PreInferenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreInferenceResult.ProtoReflect.Descriptor instead.
func (*PreInferenceResult) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{1}
}

func (x *PreInferenceResult) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PreInferenceResult) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

func (x *PreInferenceResult) GetPolicyResult() string {
	if x != nil {
		return x.PolicyResult
	}
	return ""
}

func (x *PreInferenceResult) GetPolicyVersion() int32 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *PreInferenceResult) GetBudgetRemaining() int64 {
	if x != nil && x.BudgetRemaining != nil {
		return *x.BudgetRemaining
	}
	return 0
}

func (x *PreInferenceResult) GetToolStrategy() string {
	if x != nil {
		return x.ToolStrategy
	}
	return ""
}

func (x *PreInferenceResult) GetDenialReason() string {
	if x != nil {
		return x.DenialReason
	}
	return ""
}

func (x *PreInferenceResult) GetDenialStatusCode() int32 {
	if x != nil {
		return x.DenialStatusCode
	}
	return 0
}

func (x *PreInferenceResult) GetSanitizedPrompt() string {
	if x != nil && x.SanitizedPrompt != nil {
		return *x.SanitizedPrompt
	}
	return ""
}

func (x *PreInferenceResult) GetPiiMapping() string {
	if x != nil {
		return x.PiiMapping
	}
	return ""
}

func (x *PreInferenceResult) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PreInferenceResult) GetResolvedTools() []*ToolDefinition {
	if x != nil {
		return x.ResolvedTools
	}
	return nil
}

// Request payload for EvaluatePostInference.
type PostInferenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model response content (main text).
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// Extracted reasoning/thinking content (from <think> blocks in reasoning models).
	ThinkingContent string `protobuf:"bytes,2,opt,name=thinking_content,json=thinkingContent,proto3" json:"thinking_content,omitempty"`
	// Model that generated the response.
	ModelId string `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Provider that served the response.
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	// Audit metadata accumulated during the request lifecycle.
	AuditMetadata map[string]string `protobuf:"bytes,5,rep,name=audit_metadata,json=auditMetadata,proto3" json:"audit_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tool interactions that occurred during this request (active/passive).
	ToolInteractions []*ToolInteraction `protobuf:"bytes,6,rep,name=tool_interactions,json=toolInteractions,proto3" json:"tool_interactions,omitempty"`
	// Token usage from the provider response.
	PromptTokens     int32 `protobuf:"varint,7,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32 `protobuf:"varint,8,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	// End-to-end latency in milliseconds.
	LatencyMs float64 `protobuf:"fixed64,9,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// PII mapping from pre-inference (for restoring sanitized tokens).
	PiiMapping string `protobuf:"bytes,10,opt,name=pii_mapping,json=piiMapping,proto3" json:"pii_mapping,omitempty"`
	// Session identifier.
	SessionId     string `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInferenceRequest) Reset() {
	*x = PostInferenceRequest{}
	mi := &file_governance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInferenceRequest) ProtoMessage() {}

func (x *PostInferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInferenceRequest.ProtoReflect.Descriptor instead.
func (*PostInferenceRequest) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{2}
}

func (x *PostInferenceRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostInferenceRequest) GetThinkingContent() string {
	if x != nil {
		return x.ThinkingContent
	}
	return ""
}

func (x *PostInferenceRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PostInferenceRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PostInferenceRequest) GetAuditMetadata() map[string]string {
	if x != nil {
		return x.AuditMetadata
	}
	return nil
}

func (x *PostInferenceRequest) GetToolInteractions() []*ToolInteraction {
	if x != nil {
		return x.ToolInteractions
	}
	return nil
}

func (x *PostInferenceRequest) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *PostInferenceRequest) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *PostInferenceRequest) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PostInferenceRequest) GetPiiMapping() string {
	if x != nil {
		return x.PiiMapping
	}
	return ""
}

func (x *PostInferenceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Result from EvaluatePostInference.
type PostInferenceResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall post-inference policy result ("pass", "block", "warn").
	PolicyResult string `protobuf:"bytes,1,opt,name=policy_result,json=policyResult,proto3" json:"policy_result,omitempty"`
	// Per-analyzer decisions from content analysis.
	Decisions []*PolicyDecision `protobuf:"bytes,2,rep,name=decisions,proto3" json:"decisions,omitempty"`
	// Whether the response should be blocked from reaching the caller.
	Blocked bool `protobuf:"varint,3,opt,name=blocked,proto3" json:"blocked,omitempty"`
	// Reason the response was blocked (set only when blocked=true).
	BlockReason string `protobuf:"bytes,4,opt,name=block_reason,json=blockReason,proto3" json:"block_reason,omitempty"`
	// Content with PII tokens restored (set when PII sanitization was active).
	RestoredContent *string `protobuf:"bytes,5,opt,name=restored_content,json=restoredContent,proto3,oneof" json:"restored_content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PostInferenceResult) Reset() {
	*x = PostInferenceResult{}
	mi := &file_governance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInferenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInferenceResult) ProtoMessage() {}

func (x *PostInferenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInferenceResult.ProtoReflect.Descriptor instead.
func (*PostInferenceResult) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{3}
}

func (x *PostInferenceResult) GetPolicyResult() string {
	if x != nil {
		return x.PolicyResult
	}
	return ""
}

func (x *PostInferenceResult) GetDecisions() []*PolicyDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *PostInferenceResult) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *PostInferenceResult) GetBlockReason() string {
	if x != nil {
		return x.BlockReason
	}
	return ""
}

func (x *PostInferenceResult) GetRestoredContent() string {
	if x != nil && x.RestoredContent != nil {
		return *x.RestoredContent
	}
	return ""
}

// Full execution record for dual-write to WAL + Walacor backend.
type ExecutionRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId      string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	ModelId          string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Provider         string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	PromptText       string                 `protobuf:"bytes,4,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	ResponseContent  string                 `protobuf:"bytes,5,opt,name=response_content,json=responseContent,proto3" json:"response_content,omitempty"`
	ThinkingContent  string                 `protobuf:"bytes,6,opt,name=thinking_content,json=thinkingContent,proto3" json:"thinking_content,omitempty"`
	AttestationId    string                 `protobuf:"bytes,7,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	PolicyVersion    int32                  `protobuf:"varint,8,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyResult     string                 `protobuf:"bytes,9,opt,name=policy_result,json=policyResult,proto3" json:"policy_result,omitempty"`
	LatencyMs        float64                `protobuf:"fixed64,10,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,11,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,12,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,13,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionId        string                 `protobuf:"bytes,15,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Session chain fields (populated by the sidecar after chain computation).
	SequenceNumber     int32  `protobuf:"varint,16,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	PreviousRecordHash string `protobuf:"bytes,17,opt,name=previous_record_hash,json=previousRecordHash,proto3" json:"previous_record_hash,omitempty"`
	RecordHash         string `protobuf:"bytes,18,opt,name=record_hash,json=recordHash,proto3" json:"record_hash,omitempty"`
	// Timestamp in ISO 8601 format.
	Timestamp string `protobuf:"bytes,19,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Tenant and gateway identifiers.
	TenantId  string `protobuf:"bytes,20,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	GatewayId string `protobuf:"bytes,21,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// User who made the request.
	User string `protobuf:"bytes,22,opt,name=user,proto3" json:"user,omitempty"`
	// Provider-assigned request ID.
	ProviderRequestId string `protobuf:"bytes,23,opt,name=provider_request_id,json=providerRequestId,proto3" json:"provider_request_id,omitempty"`
	// Model integrity hash from provider (if available).
	ModelHash string `protobuf:"bytes,24,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	// A/B test variant ID (if request was part of an experiment).
	VariantId string `protobuf:"bytes,25,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	// Tool interactions attached to this execution.
	ToolInteractions []*ToolInteraction `protobuf:"bytes,26,rep,name=tool_interactions,json=toolInteractions,proto3" json:"tool_interactions,omitempty"`
	// Retry lineage — execution_id of the original attempt (if this is a retry).
	RetryOf string `protobuf:"bytes,27,opt,name=retry_of,json=retryOf,proto3" json:"retry_of,omitempty"`
	// Granular timing breakdown (JSON-encoded).
	TimingsJson string `protobuf:"bytes,28,opt,name=timings_json,json=timingsJson,proto3" json:"timings_json,omitempty"`
	// Cache hit indicator.
	CacheHit            bool  `protobuf:"varint,29,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	CachedTokens        int32 `protobuf:"varint,30,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	CacheCreationTokens int32 `protobuf:"varint,31,opt,name=cache_creation_tokens,json=cacheCreationTokens,proto3" json:"cache_creation_tokens,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecutionRecord) Reset() {
	*x = ExecutionRecord{}
	mi := &file_governance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRecord) ProtoMessage() {}

func (x *ExecutionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRecord.ProtoReflect.Descriptor instead.
func (*ExecutionRecord) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionRecord) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionRecord) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ExecutionRecord) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExecutionRecord) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

func (x *ExecutionRecord) GetResponseContent() string {
	if x != nil {
		return x.ResponseContent
	}
	return ""
}

func (x *ExecutionRecord) GetThinkingContent() string {
	if x != nil {
		return x.ThinkingContent
	}
	return ""
}

func (x *ExecutionRecord) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

func (x *ExecutionRecord) GetPolicyVersion() int32 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *ExecutionRecord) GetPolicyResult() string {
	if x != nil {
		return x.PolicyResult
	}
	return ""
}

func (x *ExecutionRecord) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ExecutionRecord) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ExecutionRecord) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *ExecutionRecord) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ExecutionRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecutionRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecutionRecord) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ExecutionRecord) GetPreviousRecordHash() string {
	if x != nil {
		return x.PreviousRecordHash
	}
	return ""
}

func (x *ExecutionRecord) GetRecordHash() string {
	if x != nil {
		return x.RecordHash
	}
	return ""
}

func (x *ExecutionRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ExecutionRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExecutionRecord) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ExecutionRecord) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecutionRecord) GetProviderRequestId() string {
	if x != nil {
		return x.ProviderRequestId
	}
	return ""
}

func (x *ExecutionRecord) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *ExecutionRecord) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *ExecutionRecord) GetToolInteractions() []*ToolInteraction {
	if x != nil {
		return x.ToolInteractions
	}
	return nil
}

func (x *ExecutionRecord) GetRetryOf() string {
	if x != nil {
		return x.RetryOf
	}
	return ""
}

func (x *ExecutionRecord) GetTimingsJson() string {
	if x != nil {
		return x.TimingsJson
	}
	return ""
}

func (x *ExecutionRecord) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *ExecutionRecord) GetCachedTokens() int32 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *ExecutionRecord) GetCacheCreationTokens() int32 {
	if x != nil {
		return x.CacheCreationTokens
	}
	return 0
}

// Request the next chain values for a session.
type ChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainRequest) Reset() {
	*x = ChainRequest{}
	mi := &file_governance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainRequest) ProtoMessage() {}

func (x *ChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainRequest.ProtoReflect.Descriptor instead.
func (*ChainRequest) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{5}
}

func (x *ChainRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Next chain values returned by the sidecar.
type ChainValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Next sequence number (0 for a new session).
	SequenceNumber int32 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Hash of the previous record in the chain (GENESIS_HASH for first record).
	PreviousRecordHash string `protobuf:"bytes,2,opt,name=previous_record_hash,json=previousRecordHash,proto3" json:"previous_record_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChainValues) Reset() {
	*x = ChainValues{}
	mi := &file_governance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainValues) ProtoMessage() {}

func (x *ChainValues) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainValues.ProtoReflect.Descriptor instead.
func (*ChainValues) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{6}
}

func (x *ChainValues) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ChainValues) GetPreviousRecordHash() string {
	if x != nil {
		return x.PreviousRecordHash
	}
	return ""
}

// Commit a new link in the session chain after writing the execution record.
type ChainUpdate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExecutionId        string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	PolicyVersion      int32                  `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyResult       string                 `protobuf:"bytes,4,opt,name=policy_result,json=policyResult,proto3" json:"policy_result,omitempty"`
	Timestamp          string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SequenceNumber     int32                  `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	PreviousRecordHash string                 `protobuf:"bytes,7,opt,name=previous_record_hash,json=previousRecordHash,proto3" json:"previous_record_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChainUpdate) Reset() {
	*x = ChainUpdate{}
	mi := &file_governance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainUpdate) ProtoMessage() {}

func (x *ChainUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainUpdate.ProtoReflect.Descriptor instead.
func (*ChainUpdate) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{7}
}

func (x *ChainUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChainUpdate) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ChainUpdate) GetPolicyVersion() int32 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *ChainUpdate) GetPolicyResult() string {
	if x != nil {
		return x.PolicyResult
	}
	return ""
}

func (x *ChainUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ChainUpdate) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ChainUpdate) GetPreviousRecordHash() string {
	if x != nil {
		return x.PreviousRecordHash
	}
	return ""
}

// Result of committing a chain link.
type ChainResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA3-512 record hash computed over the canonical metadata fields.
	RecordHash string `protobuf:"bytes,1,opt,name=record_hash,json=recordHash,proto3" json:"record_hash,omitempty"`
	// Sequence number of the committed link.
	SequenceNumber int32 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChainResult) Reset() {
	*x = ChainResult{}
	mi := &file_governance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainResult) ProtoMessage() {}

func (x *ChainResult) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainResult.ProtoReflect.Descriptor instead.
func (*ChainResult) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{8}
}

func (x *ChainResult) GetRecordHash() string {
	if x != nil {
		return x.RecordHash
	}
	return ""
}

func (x *ChainResult) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// Standalone content analysis request.
type ContentPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text to analyze.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Whether this is "input" (prompt) or "output" (response) analysis.
	AnalysisType string `protobuf:"bytes,2,opt,name=analysis_type,json=analysisType,proto3" json:"analysis_type,omitempty"`
	// Model ID for context (some analyzers adjust thresholds per model).
	ModelId       string `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPayload) Reset() {
	*x = ContentPayload{}
	mi := &file_governance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPayload) ProtoMessage() {}

func (x *ContentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPayload.ProtoReflect.Descriptor instead.
func (*ContentPayload) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{9}
}

func (x *ContentPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ContentPayload) GetAnalysisType() string {
	if x != nil {
		return x.AnalysisType
	}
	return ""
}

func (x *ContentPayload) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// Content analysis result aggregated across all configured analyzers.
type AnalysisResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether any PII was detected.
	PiiDetected bool `protobuf:"varint,1,opt,name=pii_detected,json=piiDetected,proto3" json:"pii_detected,omitempty"`
	// Whether toxicity was flagged.
	ToxicityFlagged bool `protobuf:"varint,2,opt,name=toxicity_flagged,json=toxicityFlagged,proto3" json:"toxicity_flagged,omitempty"`
	// Llama Guard safety assessment result (e.g. "safe", "unsafe\nS4").
	LlamaGuardResult string `protobuf:"bytes,3,opt,name=llama_guard_result,json=llamaGuardResult,proto3" json:"llama_guard_result,omitempty"`
	// DLP (Data Loss Prevention) findings.
	DlpFindings []*DLPFinding `protobuf:"bytes,4,rep,name=dlp_findings,json=dlpFindings,proto3" json:"dlp_findings,omitempty"`
	// Per-analyzer verdicts.
	Verdicts      []*ContentVerdict `protobuf:"bytes,5,rep,name=verdicts,proto3" json:"verdicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_governance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{10}
}

func (x *AnalysisResult) GetPiiDetected() bool {
	if x != nil {
		return x.PiiDetected
	}
	return false
}

func (x *AnalysisResult) GetToxicityFlagged() bool {
	if x != nil {
		return x.ToxicityFlagged
	}
	return false
}

func (x *AnalysisResult) GetLlamaGuardResult() string {
	if x != nil {
		return x.LlamaGuardResult
	}
	return ""
}

func (x *AnalysisResult) GetDlpFindings() []*DLPFinding {
	if x != nil {
		return x.DlpFindings
	}
	return nil
}

func (x *AnalysisResult) GetVerdicts() []*ContentVerdict {
	if x != nil {
		return x.Verdicts
	}
	return nil
}

// A single DLP finding (e.g. credit card number, API key).
type DLPFinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of sensitive data found (e.g. "credit_card", "aws_access_key").
	FindingType string `protobuf:"bytes,1,opt,name=finding_type,json=findingType,proto3" json:"finding_type,omitempty"`
	// Confidence score (0.0 – 1.0).
	Confidence float64 `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Character offset range in the source text.
	StartOffset   int32 `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     int32 `protobuf:"varint,4,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DLPFinding) Reset() {
	*x = DLPFinding{}
	mi := &file_governance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLPFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLPFinding) ProtoMessage() {}

func (x *DLPFinding) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLPFinding.ProtoReflect.Descriptor instead.
func (*DLPFinding) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{11}
}

func (x *DLPFinding) GetFindingType() string {
	if x != nil {
		return x.FindingType
	}
	return ""
}

func (x *DLPFinding) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DLPFinding) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *DLPFinding) GetEndOffset() int32 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

// Per-analyzer verdict in the analysis result.
type ContentVerdict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Analyzer identifier (e.g. "walacor.pii.v1", "llama_guard_3").
	AnalyzerId string `protobuf:"bytes,1,opt,name=analyzer_id,json=analyzerId,proto3" json:"analyzer_id,omitempty"`
	// Verdict: "pass", "warn", or "block".
	Verdict string `protobuf:"bytes,2,opt,name=verdict,proto3" json:"verdict,omitempty"`
	// Confidence score (0.0 – 1.0).
	Confidence float64 `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Safety category (e.g. "pii", "toxicity", "child_safety").
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// Human-readable reason.
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentVerdict) Reset() {
	*x = ContentVerdict{}
	mi := &file_governance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentVerdict) ProtoMessage() {}

func (x *ContentVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentVerdict.ProtoReflect.Descriptor instead.
func (*ContentVerdict) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{12}
}

func (x *ContentVerdict) GetAnalyzerId() string {
	if x != nil {
		return x.AnalyzerId
	}
	return ""
}

func (x *ContentVerdict) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *ContentVerdict) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ContentVerdict) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ContentVerdict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// A tool definition in OpenAI function-calling format.
type ToolDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name (e.g. "web_search", "get_weather").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description of what the tool does.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema for the tool's input parameters (JSON-encoded string).
	InputSchemaJson string `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	// Name of the MCP server or built-in client providing this tool.
	ServerName    string `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_governance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{13}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

func (x *ToolDefinition) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

// Request to execute a tool.
type ToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name to invoke.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Tool arguments (JSON-encoded string).
	ArgumentsJson string `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// Maximum execution time in milliseconds.
	TimeoutMs     int32 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_governance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{14}
}

func (x *ToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ToolRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// Result of a tool execution.
type ToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool output content (text or JSON-encoded).
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// Whether the tool call resulted in an error.
	IsError bool `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// Execution duration in milliseconds.
	DurationMs float64 `protobuf:"fixed64,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Cited source URLs (populated by web_search and similar tools).
	Sources       []*ToolSource `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_governance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{15}
}

func (x *ToolResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ToolResponse) GetSources() []*ToolSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

// A source citation from a tool result (e.g. web search result).
type ToolSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolSource) Reset() {
	*x = ToolSource{}
	mi := &file_governance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSource) ProtoMessage() {}

func (x *ToolSource) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSource.ProtoReflect.Descriptor instead.
func (*ToolSource) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{16}
}

func (x *ToolSource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ToolSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ToolSource) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

// A tool interaction record for the audit trail.
type ToolInteraction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-assigned tool call ID (e.g. "call_abc123").
	ToolId string `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	// Tool type ("function", "web_search", "code_interpreter", "file_search").
	ToolType string `protobuf:"bytes,2,opt,name=tool_type,json=toolType,proto3" json:"tool_type,omitempty"`
	// Tool/function name.
	ToolName string `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Input data sent to the tool (JSON-encoded).
	InputData string `protobuf:"bytes,4,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	// Output data returned from the tool (JSON-encoded).
	OutputData string `protobuf:"bytes,5,opt,name=output_data,json=outputData,proto3" json:"output_data,omitempty"`
	// SHA3-512 hash of the input data.
	InputHash string `protobuf:"bytes,6,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	// SHA3-512 hash of the output data.
	OutputHash string `protobuf:"bytes,7,opt,name=output_hash,json=outputHash,proto3" json:"output_hash,omitempty"`
	// Cited sources from the tool (for web_search, etc.).
	Sources []*ToolSource `protobuf:"bytes,8,rep,name=sources,proto3" json:"sources,omitempty"`
	// Execution duration in milliseconds.
	DurationMs float64 `protobuf:"fixed64,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Content analysis results on the tool output (analyzer_id -> verdict JSON).
	ContentAnalysis map[string]string `protobuf:"bytes,10,rep,name=content_analysis,json=contentAnalysis,proto3" json:"content_analysis,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tool loop iteration number (1-based).
	Iteration int32 `protobuf:"varint,11,opt,name=iteration,proto3" json:"iteration,omitempty"`
	// Whether the tool call resulted in an error.
	IsError       bool `protobuf:"varint,12,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInteraction) Reset() {
	*x = ToolInteraction{}
	mi := &file_governance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInteraction) ProtoMessage() {}

func (x *ToolInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInteraction.ProtoReflect.Descriptor instead.
func (*ToolInteraction) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{17}
}

func (x *ToolInteraction) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolInteraction) GetToolType() string {
	if x != nil {
		return x.ToolType
	}
	return ""
}

func (x *ToolInteraction) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolInteraction) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *ToolInteraction) GetOutputData() string {
	if x != nil {
		return x.OutputData
	}
	return ""
}

func (x *ToolInteraction) GetInputHash() string {
	if x != nil {
		return x.InputHash
	}
	return ""
}

func (x *ToolInteraction) GetOutputHash() string {
	if x != nil {
		return x.OutputHash
	}
	return ""
}

func (x *ToolInteraction) GetSources() []*ToolSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ToolInteraction) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ToolInteraction) GetContentAnalysis() map[string]string {
	if x != nil {
		return x.ContentAnalysis
	}
	return nil
}

func (x *ToolInteraction) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *ToolInteraction) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// Semantic cache lookup key.
type CacheKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prompt text to look up.
	PromptText string `protobuf:"bytes,1,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	// Model ID for cache scoping (different models produce different responses).
	ModelId       string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheKey) Reset() {
	*x = CacheKey{}
	mi := &file_governance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheKey) ProtoMessage() {}

func (x *CacheKey) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheKey.ProtoReflect.Descriptor instead.
func (*CacheKey) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{18}
}

func (x *CacheKey) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

func (x *CacheKey) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// Semantic cache lookup result.
type CacheResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether a cache entry was found.
	Hit bool `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`
	// Cached response body (JSON-encoded; empty if hit=false).
	ResponseBody string `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	// When the cache entry was stored (ISO 8601; empty if hit=false).
	CachedAt      string `protobuf:"bytes,3,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResponse) Reset() {
	*x = CacheResponse{}
	mi := &file_governance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResponse) ProtoMessage() {}

func (x *CacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResponse.ProtoReflect.Descriptor instead.
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{19}
}

func (x *CacheResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *CacheResponse) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *CacheResponse) GetCachedAt() string {
	if x != nil {
		return x.CachedAt
	}
	return ""
}

// Semantic cache store request.
type CachePutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prompt text (cache key).
	PromptText string `protobuf:"bytes,1,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	// Model ID (cache key scope).
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Response body to cache (JSON-encoded).
	ResponseBody  string `protobuf:"bytes,3,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachePutRequest) Reset() {
	*x = CachePutRequest{}
	mi := &file_governance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachePutRequest) ProtoMessage() {}

func (x *CachePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachePutRequest.ProtoReflect.Descriptor instead.
func (*CachePutRequest) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{20}
}

func (x *CachePutRequest) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

func (x *CachePutRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CachePutRequest) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

// Result of a cache store operation.
type CacheResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResult) Reset() {
	*x = CacheResult{}
	mi := &file_governance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResult) ProtoMessage() {}

func (x *CacheResult) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResult.ProtoReflect.Descriptor instead.
func (*CacheResult) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{21}
}

func (x *CacheResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Policy evaluation decision (used in post-inference results).
type PolicyDecision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy name or rule identifier.
	PolicyName string `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	// Evaluation result ("pass", "warn", "block").
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	// Human-readable details about the decision.
	Details       string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyDecision) Reset() {
	*x = PolicyDecision{}
	mi := &file_governance_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDecision) ProtoMessage() {}

func (x *PolicyDecision) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDecision.ProtoReflect.Descriptor instead.
func (*PolicyDecision) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{22}
}

func (x *PolicyDecision) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *PolicyDecision) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *PolicyDecision) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// Result of writing an execution record.
type WriteResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the write succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Execution ID assigned to the record.
	ExecutionId string `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Error message (set only when success=false).
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResult) Reset() {
	*x = WriteResult{}
	mi := &file_governance_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResult) ProtoMessage() {}

func (x *WriteResult) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResult.ProtoReflect.Descriptor instead.
func (*WriteResult) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{23}
}

func (x *WriteResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResult) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *WriteResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Empty request (for HealthCheck).
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_governance_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{24}
}

// Sidecar health status.
type HealthStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the sidecar is healthy and ready to serve.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Sidecar version string.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Per-model capability cache (model_id -> JSON-encoded capabilities).
	ModelCapabilities map[string]string `protobuf:"bytes,3,rep,name=model_capabilities,json=modelCapabilities,proto3" json:"model_capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Number of active sessions in the chain tracker.
	ActiveSessions int32 `protobuf:"varint,4,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	// Sidecar uptime in seconds.
	UptimeSeconds float64 `protobuf:"fixed64,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Number of configured content analyzers.
	ContentAnalyzerCount int32 `protobuf:"varint,6,opt,name=content_analyzer_count,json=contentAnalyzerCount,proto3" json:"content_analyzer_count,omitempty"`
	// Whether governance is enabled (vs. transparent proxy / audit-only).
	GovernanceEnabled bool `protobuf:"varint,7,opt,name=governance_enabled,json=governanceEnabled,proto3" json:"governance_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_governance_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{25}
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthStatus) GetModelCapabilities() map[string]string {
	if x != nil {
		return x.ModelCapabilities
	}
	return nil
}

func (x *HealthStatus) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *HealthStatus) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthStatus) GetContentAnalyzerCount() int32 {
	if x != nil {
		return x.ContentAnalyzerCount
	}
	return 0
}

func (x *HealthStatus) GetGovernanceEnabled() bool {
	if x != nil {
		return x.GovernanceEnabled
	}
	return false
}

var File_governance_proto protoreflect.FileDescriptor

const file_governance_proto_rawDesc = "" +
	"\n" +
	"\x10governance.proto\x12\x15walacor.governance.v1\"\xf2\x03\n" +
	"\x13PreInferenceRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1f\n" +
	"\vprompt_text\x18\x04 \x01(\tR\n" +
	"promptText\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12T\n" +
	"\bmetadata\x18\a \x03(\v28.walacor.governance.v1.PreInferenceRequest.MetadataEntryR\bmetadata\x12;\n" +
	"\x05tools\x18\b \x03(\v2%.walacor.governance.v1.ToolDefinitionR\x05tools\x12!\n" +
	"\frequest_type\x18\t \x01(\tR\vrequestType\x12\"\n" +
	"\rab_tests_json\x18\n" +
	" \x01(\tR\vabTestsJson\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x04\n" +
	"\x12PreInferenceResult\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12%\n" +
	"\x0eattestation_id\x18\x02 \x01(\tR\rattestationId\x12#\n" +
	"\rpolicy_result\x18\x03 \x01(\tR\fpolicyResult\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\x05R\rpolicyVersion\x12.\n" +
	"\x10budget_remaining\x18\x05 \x01(\x03H\x00R\x0fbudgetRemaining\x88\x01\x01\x12#\n" +
	"\rtool_strategy\x18\x06 \x01(\tR\ftoolStrategy\x12#\n" +
	"\rdenial_reason\x18\a \x01(\tR\fdenialReason\x12,\n" +
	"\x12denial_status_code\x18\b \x01(\x05R\x10denialStatusCode\x12.\n" +
	"\x10sanitized_prompt\x18\t \x01(\tH\x01R\x0fsanitizedPrompt\x88\x01\x01\x12\x1f\n" +
	"\vpii_mapping\x18\n" +
	" \x01(\tR\n" +
	"piiMapping\x12\x19\n" +
	"\bmodel_id\x18\v \x01(\tR\amodelId\x12L\n" +
	"\x0eresolved_tools\x18\f \x03(\v2%.walacor.governance.v1.ToolDefinitionR\rresolvedToolsB\x13\n" +
	"\x11_budget_remainingB\x13\n" +
	"\x11_sanitized_prompt\"\xc1\x04\n" +
	"\x14PostInferenceRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12)\n" +
	"\x10thinking_content\x18\x02 \x01(\tR\x0fthinkingContent\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12e\n" +
	"\x0eaudit_metadata\x18\x05 \x03(\v2>.walacor.governance.v1.PostInferenceRequest.AuditMetadataEntryR\rauditMetadata\x12S\n" +
	"\x11tool_interactions\x18\x06 \x03(\v2&.walacor.governance.v1.ToolInteractionR\x10toolInteractions\x12#\n" +
	"\rprompt_tokens\x18\a \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\b \x01(\x05R\x10completionTokens\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\t \x01(\x01R\tlatencyMs\x12\x1f\n" +
	"\vpii_mapping\x18\n" +
	" \x01(\tR\n" +
	"piiMapping\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\x1a@\n" +
	"\x12AuditMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\x13PostInferenceResult\x12#\n" +
	"\rpolicy_result\x18\x01 \x01(\tR\fpolicyResult\x12C\n" +
	"\tdecisions\x18\x02 \x03(\v2%.walacor.governance.v1.PolicyDecisionR\tdecisions\x12\x18\n" +
	"\ablocked\x18\x03 \x01(\bR\ablocked\x12!\n" +
	"\fblock_reason\x18\x04 \x01(\tR\vblockReason\x12.\n" +
	"\x10restored_content\x18\x05 \x01(\tH\x00R\x0frestoredContent\x88\x01\x01B\x13\n" +
	"\x11_restored_content\"\xf8\t\n" +
	"\x0fExecutionRecord\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1f\n" +
	"\vprompt_text\x18\x04 \x01(\tR\n" +
	"promptText\x12)\n" +
	"\x10response_content\x18\x05 \x01(\tR\x0fresponseContent\x12)\n" +
	"\x10thinking_content\x18\x06 \x01(\tR\x0fthinkingContent\x12%\n" +
	"\x0eattestation_id\x18\a \x01(\tR\rattestationId\x12%\n" +
	"\x0epolicy_version\x18\b \x01(\x05R\rpolicyVersion\x12#\n" +
	"\rpolicy_result\x18\t \x01(\tR\fpolicyResult\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\n" +
	" \x01(\x01R\tlatencyMs\x12#\n" +
	"\rprompt_tokens\x18\v \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\f \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\r \x01(\x05R\vtotalTokens\x12P\n" +
	"\bmetadata\x18\x0e \x03(\v24.walacor.governance.v1.ExecutionRecord.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"session_id\x18\x0f \x01(\tR\tsessionId\x12'\n" +
	"\x0fsequence_number\x18\x10 \x01(\x05R\x0esequenceNumber\x120\n" +
	"\x14previous_record_hash\x18\x11 \x01(\tR\x12previousRecordHash\x12\x1f\n" +
	"\vrecord_hash\x18\x12 \x01(\tR\n" +
	"recordHash\x12\x1c\n" +
	"\ttimestamp\x18\x13 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\ttenant_id\x18\x14 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x15 \x01(\tR\tgatewayId\x12\x12\n" +
	"\x04user\x18\x16 \x01(\tR\x04user\x12.\n" +
	"\x13provider_request_id\x18\x17 \x01(\tR\x11providerRequestId\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x18 \x01(\tR\tmodelHash\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x19 \x01(\tR\tvariantId\x12S\n" +
	"\x11tool_interactions\x18\x1a \x03(\v2&.walacor.governance.v1.ToolInteractionR\x10toolInteractions\x12\x19\n" +
	"\bretry_of\x18\x1b \x01(\tR\aretryOf\x12!\n" +
	"\ftimings_json\x18\x1c \x01(\tR\vtimingsJson\x12\x1b\n" +
	"\tcache_hit\x18\x1d \x01(\bR\bcacheHit\x12#\n" +
	"\rcached_tokens\x18\x1e \x01(\x05R\fcachedTokens\x122\n" +
	"\x15cache_creation_tokens\x18\x1f \x01(\x05R\x13cacheCreationTokens\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\fChainRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"h\n" +
	"\vChainValues\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x05R\x0esequenceNumber\x120\n" +
	"\x14previous_record_hash\x18\x02 \x01(\tR\x12previousRecordHash\"\x94\x02\n" +
	"\vChainUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x05R\rpolicyVersion\x12#\n" +
	"\rpolicy_result\x18\x04 \x01(\tR\fpolicyResult\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12'\n" +
	"\x0fsequence_number\x18\x06 \x01(\x05R\x0esequenceNumber\x120\n" +
	"\x14previous_record_hash\x18\a \x01(\tR\x12previousRecordHash\"W\n" +
	"\vChainResult\x12\x1f\n" +
	"\vrecord_hash\x18\x01 \x01(\tR\n" +
	"recordHash\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\"d\n" +
	"\x0eContentPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\ranalysis_type\x18\x02 \x01(\tR\fanalysisType\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\"\x95\x02\n" +
	"\x0eAnalysisResult\x12!\n" +
	"\fpii_detected\x18\x01 \x01(\bR\vpiiDetected\x12)\n" +
	"\x10toxicity_flagged\x18\x02 \x01(\bR\x0ftoxicityFlagged\x12,\n" +
	"\x12llama_guard_result\x18\x03 \x01(\tR\x10llamaGuardResult\x12D\n" +
	"\fdlp_findings\x18\x04 \x03(\v2!.walacor.governance.v1.DLPFindingR\vdlpFindings\x12A\n" +
	"\bverdicts\x18\x05 \x03(\v2%.walacor.governance.v1.ContentVerdictR\bverdicts\"\x91\x01\n" +
	"\n" +
	"DLPFinding\x12!\n" +
	"\ffinding_type\x18\x01 \x01(\tR\vfindingType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12!\n" +
	"\fstart_offset\x18\x03 \x01(\x05R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x04 \x01(\x05R\tendOffset\"\x9f\x01\n" +
	"\x0eContentVerdict\x12\x1f\n" +
	"\vanalyzer_id\x18\x01 \x01(\tR\n" +
	"analyzerId\x12\x18\n" +
	"\averdict\x18\x02 \x01(\tR\averdict\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x93\x01\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\tR\x0finputSchemaJson\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\"g\n" +
	"\vToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"\xa1\x01\n" +
	"\fToolResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x01R\n" +
	"durationMs\x12;\n" +
	"\asources\x18\x04 \x03(\v2!.walacor.governance.v1.ToolSourceR\asources\"N\n" +
	"\n" +
	"ToolSource\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\"\xa7\x04\n" +
	"\x0fToolInteraction\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x1b\n" +
	"\ttool_type\x18\x02 \x01(\tR\btoolType\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"input_data\x18\x04 \x01(\tR\tinputData\x12\x1f\n" +
	"\voutput_data\x18\x05 \x01(\tR\n" +
	"outputData\x12\x1d\n" +
	"\n" +
	"input_hash\x18\x06 \x01(\tR\tinputHash\x12\x1f\n" +
	"\voutput_hash\x18\a \x01(\tR\n" +
	"outputHash\x12;\n" +
	"\asources\x18\b \x03(\v2!.walacor.governance.v1.ToolSourceR\asources\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x01R\n" +
	"durationMs\x12f\n" +
	"\x10content_analysis\x18\n" +
	" \x03(\v2;.walacor.governance.v1.ToolInteraction.ContentAnalysisEntryR\x0fcontentAnalysis\x12\x1c\n" +
	"\titeration\x18\v \x01(\x05R\titeration\x12\x19\n" +
	"\bis_error\x18\f \x01(\bR\aisError\x1aB\n" +
	"\x14ContentAnalysisEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\bCacheKey\x12\x1f\n" +
	"\vprompt_text\x18\x01 \x01(\tR\n" +
	"promptText\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\"c\n" +
	"\rCacheResponse\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x12#\n" +
	"\rresponse_body\x18\x02 \x01(\tR\fresponseBody\x12\x1b\n" +
	"\tcached_at\x18\x03 \x01(\tR\bcachedAt\"r\n" +
	"\x0fCachePutRequest\x12\x1f\n" +
	"\vprompt_text\x18\x01 \x01(\tR\n" +
	"promptText\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12#\n" +
	"\rresponse_body\x18\x03 \x01(\tR\fresponseBody\"'\n" +
	"\vCacheResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x0ePolicyDecision\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"o\n" +
	"\vWriteResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\a\n" +
	"\x05Empty\"\xa8\x03\n" +
	"\fHealthStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12i\n" +
	"\x12model_capabilities\x18\x03 \x03(\v2:.walacor.governance.v1.HealthStatus.ModelCapabilitiesEntryR\x11modelCapabilities\x12'\n" +
	"\x0factive_sessions\x18\x04 \x01(\x05R\x0eactiveSessions\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x01R\ruptimeSeconds\x124\n" +
	"\x16content_analyzer_count\x18\x06 \x01(\x05R\x14contentAnalyzerCount\x12-\n" +
	"\x12governance_enabled\x18\a \x01(\bR\x11governanceEnabled\x1aD\n" +
	"\x16ModelCapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xba\a\n" +
	"\x10GovernanceEngine\x12m\n" +
	"\x14EvaluatePreInference\x12*.walacor.governance.v1.PreInferenceRequest\x1a).walacor.governance.v1.PreInferenceResult\x12p\n" +
	"\x15EvaluatePostInference\x12+.walacor.governance.v1.PostInferenceRequest\x1a*.walacor.governance.v1.PostInferenceResult\x12]\n" +
	"\x0fRecordExecution\x12&.walacor.governance.v1.ExecutionRecord\x1a\".walacor.governance.v1.WriteResult\x12Z\n" +
	"\x0fNextChainValues\x12#.walacor.governance.v1.ChainRequest\x1a\".walacor.governance.v1.ChainValues\x12U\n" +
	"\vUpdateChain\x12\".walacor.governance.v1.ChainUpdate\x1a\".walacor.governance.v1.ChainResult\x12^\n" +
	"\x0eAnalyzeContent\x12%.walacor.governance.v1.ContentPayload\x1a%.walacor.governance.v1.AnalysisResult\x12V\n" +
	"\vExecuteTool\x12\".walacor.governance.v1.ToolRequest\x1a#.walacor.governance.v1.ToolResponse\x12Q\n" +
	"\bCacheGet\x12\x1f.walacor.governance.v1.CacheKey\x1a$.walacor.governance.v1.CacheResponse\x12V\n" +
	"\bCachePut\x12&.walacor.governance.v1.CachePutRequest\x1a\".walacor.governance.v1.CacheResult\x12P\n" +
	"\vHealthCheck\x12\x1c.walacor.governance.v1.Empty\x1a#.walacor.governance.v1.HealthStatusB\n" +
	"Z\bproxy/pbb\x06proto3"

var (
	file_governance_proto_rawDescOnce sync.Once
	file_governance_proto_rawDescData []byte
)

func file_governance_proto_rawDescGZIP() []byte {
	file_governance_proto_rawDescOnce.Do(func() {
		file_governance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_governance_proto_rawDesc), len(file_governance_proto_rawDesc)))
	})
	return file_governance_proto_rawDescData
}

var file_governance_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_governance_proto_goTypes = []any{
	(*PreInferenceRequest)(nil),  // 0: walacor.governance.v1.PreInferenceRequest
	(*PreInferenceResult)(nil),   // 1: walacor.governance.v1.PreInferenceResult
	(*PostInferenceRequest)(nil), // 2: walacor.governance.v1.PostInferenceRequest
	(*PostInferenceResult)(nil),  // 3: walacor.governance.v1.PostInferenceResult
	(*ExecutionRecord)(nil),      // 4: walacor.governance.v1.ExecutionRecord
	(*ChainRequest)(nil),         // 5: walacor.governance.v1.ChainRequest
	(*ChainValues)(nil),          // 6: walacor.governance.v1.ChainValues
	(*ChainUpdate)(nil),          // 7: walacor.governance.v1.ChainUpdate
	(*ChainResult)(nil),          // 8: walacor.governance.v1.ChainResult
	(*ContentPayload)(nil),       // 9: walacor.governance.v1.ContentPayload
	(*AnalysisResult)(nil),       // 10: walacor.governance.v1.AnalysisResult
	(*DLPFinding)(nil),           // 11: walacor.governance.v1.DLPFinding
	(*ContentVerdict)(nil),       // 12: walacor.governance.v1.ContentVerdict
	(*ToolDefinition)(nil),       // 13: walacor.governance.v1.ToolDefinition
	(*ToolRequest)(nil),          // 14: walacor.governance.v1.ToolRequest
	(*ToolResponse)(nil),         // 15: walacor.governance.v1.ToolResponse
	(*ToolSource)(nil),           // 16: walacor.governance.v1.ToolSource
	(*ToolInteraction)(nil),      // 17: walacor.governance.v1.ToolInteraction
	(*CacheKey)(nil),             // 18: walacor.governance.v1.CacheKey
	(*CacheResponse)(nil),        // 19: walacor.governance.v1.CacheResponse
	(*CachePutRequest)(nil),      // 20: walacor.governance.v1.CachePutRequest
	(*CacheResult)(nil),          // 21: walacor.governance.v1.CacheResult
	(*PolicyDecision)(nil),       // 22: walacor.governance.v1.PolicyDecision
	(*WriteResult)(nil),          // 23: walacor.governance.v1.WriteResult
	(*Empty)(nil),                // 24: walacor.governance.v1.Empty
	(*HealthStatus)(nil),         // 25: walacor.governance.v1.HealthStatus
	nil,                          // 26: walacor.governance.v1.PreInferenceRequest.MetadataEntry
	nil,                          // 27: walacor.governance.v1.PostInferenceRequest.AuditMetadataEntry
	nil,                          // 28: walacor.governance.v1.ExecutionRecord.MetadataEntry
	nil,                          // 29: walacor.governance.v1.ToolInteraction.ContentAnalysisEntry
	nil,                          // 30: walacor.governance.v1.HealthStatus.ModelCapabilitiesEntry
}
var file_governance_proto_depIdxs = []int32{
	26, // 0: walacor.governance.v1.PreInferenceRequest.metadata:type_name -> walacor.governance.v1.PreInferenceRequest.MetadataEntry
	13, // 1: walacor.governance.v1.PreInferenceRequest.tools:type_name -> walacor.governance.v1.ToolDefinition
	13, // 2: walacor.governance.v1.PreInferenceResult.resolved_tools:type_name -> walacor.governance.v1.ToolDefinition
	27, // 3: walacor.governance.v1.PostInferenceRequest.audit_metadata:type_name -> walacor.governance.v1.PostInferenceRequest.AuditMetadataEntry
	17, // 4: walacor.governance.v1.PostInferenceRequest.tool_interactions:type_name -> walacor.governance.v1.ToolInteraction
	22, // 5: walacor.governance.v1.PostInferenceResult.decisions:type_name -> walacor.governance.v1.PolicyDecision
	28, // 6: walacor.governance.v1.ExecutionRecord.metadata:type_name -> walacor.governance.v1.ExecutionRecord.MetadataEntry
	17, // 7: walacor.governance.v1.ExecutionRecord.tool_interactions:type_name -> walacor.governance.v1.ToolInteraction
	11, // 8: walacor.governance.v1.AnalysisResult.dlp_findings:type_name -> walacor.governance.v1.DLPFinding
	12, // 9: walacor.governance.v1.AnalysisResult.verdicts:type_name -> walacor.governance.v1.ContentVerdict
	16, // 10: walacor.governance.v1.ToolResponse.sources:type_name -> walacor.governance.v1.ToolSource
	16, // 11: walacor.governance.v1.ToolInteraction.sources:type_name -> walacor.governance.v1.ToolSource
	29, // 12: walacor.governance.v1.ToolInteraction.content_analysis:type_name -> walacor.governance.v1.ToolInteraction.ContentAnalysisEntry
	30, // 13: walacor.governance.v1.HealthStatus.model_capabilities:type_name -> walacor.governance.v1.HealthStatus.ModelCapabilitiesEntry
	0,  // 14: walacor.governance.v1.GovernanceEngine.EvaluatePreInference:input_type -> walacor.governance.v1.PreInferenceRequest
	2,  // 15: walacor.governance.v1.GovernanceEngine.EvaluatePostInference:input_type -> walacor.governance.v1.PostInferenceRequest
	4,  // 16: walacor.governance.v1.GovernanceEngine.RecordExecution:input_type -> walacor.governance.v1.ExecutionRecord
	5,  // 17: walacor.governance.v1.GovernanceEngine.NextChainValues:input_type -> walacor.governance.v1.ChainRequest
	7,  // 18: walacor.governance.v1.GovernanceEngine.UpdateChain:input_type -> walacor.governance.v1.ChainUpdate
	9,  // 19: walacor.governance.v1.GovernanceEngine.AnalyzeContent:input_type -> walacor.governance.v1.ContentPayload
	14, // 20: walacor.governance.v1.GovernanceEngine.ExecuteTool:input_type -> walacor.governance.v1.ToolRequest
	18, // 21: walacor.governance.v1.GovernanceEngine.CacheGet:input_type -> walacor.governance.v1.CacheKey
	20, // 22: walacor.governance.v1.GovernanceEngine.CachePut:input_type -> walacor.governance.v1.CachePutRequest
	24, // 23: walacor.governance.v1.GovernanceEngine.HealthCheck:input_type -> walacor.governance.v1.Empty
	1,  // 24: walacor.governance.v1.GovernanceEngine.EvaluatePreInference:output_type -> walacor.governance.v1.PreInferenceResult
	3,  // 25: walacor.governance.v1.GovernanceEngine.EvaluatePostInference:output_type -> walacor.governance.v1.PostInferenceResult
	23, // 26: walacor.governance.v1.GovernanceEngine.RecordExecution:output_type -> walacor.governance.v1.WriteResult
	6,  // 27: walacor.governance.v1.GovernanceEngine.NextChainValues:output_type -> walacor.governance.v1.ChainValues
	8,  // 28: walacor.governance.v1.GovernanceEngine.UpdateChain:output_type -> walacor.governance.v1.ChainResult
	10, // 29: walacor.governance.v1.GovernanceEngine.AnalyzeContent:output_type -> walacor.governance.v1.AnalysisResult
	15, // 30: walacor.governance.v1.GovernanceEngine.ExecuteTool:output_type -> walacor.governance.v1.ToolResponse
	19, // 31: walacor.governance.v1.GovernanceEngine.CacheGet:output_type -> walacor.governance.v1.CacheResponse
	21, // 32: walacor.governance.v1.GovernanceEngine.CachePut:output_type -> walacor.governance.v1.CacheResult
	25, // 33: walacor.governance.v1.GovernanceEngine.HealthCheck:output_type -> walacor.governance.v1.HealthStatus
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_governance_proto_init() }
func file_governance_proto_init() {
	if File_governance_proto != nil {
		return
	}
	file_governance_proto_msgTypes[1].OneofWrappers = []any{}
	file_governance_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_governance_proto_rawDesc), len(file_governance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_governance_proto_goTypes,
		DependencyIndexes: file_governance_proto_depIdxs,
		MessageInfos:      file_governance_proto_msgTypes,
	}.Build()
	File_governance_proto = out.File
	file_governance_proto_goTypes = nil
	file_governance_proto_depIdxs = nil
}
