// Walacor Gateway — gRPC interface between Go proxy and Python governance sidecar.
//
// The Go proxy handles HTTP ingress, TLS, connection pooling, and LLM provider
// forwarding.  All governance intelligence (policy evaluation, content analysis,
// session chains, audit hashing, tool execution, caching) lives in the Python
// sidecar and is accessed via this service.
//
// Wire format: proto3.  Transport: gRPC over Unix domain socket (default) or TCP.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: governance.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GovernanceEngine_EvaluatePreInference_FullMethodName  = "/walacor.governance.v1.GovernanceEngine/EvaluatePreInference"
	GovernanceEngine_EvaluatePostInference_FullMethodName = "/walacor.governance.v1.GovernanceEngine/EvaluatePostInference"
	GovernanceEngine_RecordExecution_FullMethodName       = "/walacor.governance.v1.GovernanceEngine/RecordExecution"
	GovernanceEngine_NextChainValues_FullMethodName       = "/walacor.governance.v1.GovernanceEngine/NextChainValues"
	GovernanceEngine_UpdateChain_FullMethodName           = "/walacor.governance.v1.GovernanceEngine/UpdateChain"
	GovernanceEngine_AnalyzeContent_FullMethodName        = "/walacor.governance.v1.GovernanceEngine/AnalyzeContent"
	GovernanceEngine_ExecuteTool_FullMethodName           = "/walacor.governance.v1.GovernanceEngine/ExecuteTool"
	GovernanceEngine_CacheGet_FullMethodName              = "/walacor.governance.v1.GovernanceEngine/CacheGet"
	GovernanceEngine_CachePut_FullMethodName              = "/walacor.governance.v1.GovernanceEngine/CachePut"
	GovernanceEngine_HealthCheck_FullMethodName           = "/walacor.governance.v1.GovernanceEngine/HealthCheck"
)

// GovernanceEngineClient is the client API for GovernanceEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GovernanceEngineClient interface {
	// Pre-inference evaluation: authenticate caller, check model attestation,
	// evaluate pre-inference policies, verify budget, sanitize PII if enabled,
	// and resolve A/B test variants.  Called before the Go proxy forwards the
	// request to the LLM provider.
	EvaluatePreInference(ctx context.Context, in *PreInferenceRequest, opts ...grpc.CallOption) (*PreInferenceResult, error)
	// Post-inference evaluation: run content analyzers (PII, toxicity, Llama Guard,
	// DLP) on the model response, evaluate post-inference policies, and restore
	// PII-sanitized tokens if applicable.  Called after the Go proxy receives the
	// LLM provider response.
	EvaluatePostInference(ctx context.Context, in *PostInferenceRequest, opts ...grpc.CallOption) (*PostInferenceResult, error)
	// Persist an execution record to WAL + Walacor backend (dual-write).
	// Fire-and-forget from the Go proxy side — the sidecar handles retries.
	RecordExecution(ctx context.Context, in *ExecutionRecord, opts ...grpc.CallOption) (*WriteResult, error)
	// Session chain: get the next (sequence_number, previous_record_hash) for a
	// session's Merkle chain.  Called before building the execution record.
	NextChainValues(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*ChainValues, error)
	// Session chain: commit a new link after the execution record is written.
	UpdateChain(ctx context.Context, in *ChainUpdate, opts ...grpc.CallOption) (*ChainResult, error)
	// Standalone content analysis — can run in parallel with the LLM call for
	// prompt-side analysis while the provider is processing.
	AnalyzeContent(ctx context.Context, in *ContentPayload, opts ...grpc.CallOption) (*AnalysisResult, error)
	// Execute a tool (MCP server tool or built-in like web_search).
	// Used when the Go proxy detects tool_calls in the LLM response and the
	// tool strategy is "active".
	ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error)
	// Semantic cache lookup — check if an equivalent prompt was recently served.
	CacheGet(ctx context.Context, in *CacheKey, opts ...grpc.CallOption) (*CacheResponse, error)
	// Semantic cache store — save a response for future cache hits.
	CachePut(ctx context.Context, in *CachePutRequest, opts ...grpc.CallOption) (*CacheResult, error)
	// Health check — used by Go proxy readiness probes and startup sequencing.
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
}

type governanceEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewGovernanceEngineClient(cc grpc.ClientConnInterface) GovernanceEngineClient {
	return &governanceEngineClient{cc}
}

func (c *governanceEngineClient) EvaluatePreInference(ctx context.Context, in *PreInferenceRequest, opts ...grpc.CallOption) (*PreInferenceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreInferenceResult)
	err := c.cc.Invoke(ctx, GovernanceEngine_EvaluatePreInference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceEngineClient) EvaluatePostInference(ctx context.Context, in *PostInferenceRequest, opts ...grpc.CallOption) (*PostInferenceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostInferenceResult)
	err := c.cc.Invoke(ctx, GovernanceEngine_EvaluatePostInference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceEngineClient) RecordExecution(ctx context.Context, in *ExecutionRecord, opts ...grpc.CallOption) (*WriteResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResult)
	err := c.cc.Invoke(ctx, GovernanceEngine_RecordExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceEngineClient) NextChainValues(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*ChainValues, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainValues)
	err := c.cc.Invoke(ctx, GovernanceEngine_NextChainValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceEngineClient) UpdateChain(ctx context.Context, in *ChainUpdate, opts ...grpc.CallOption) (*ChainResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainResult)
	err := c.cc.Invoke(ctx, GovernanceEngine_UpdateChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceEngineClient) AnalyzeContent(ctx context.Context, in *ContentPayload, opts ...grpc.CallOption) (*AnalysisResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisResult)
	err := c.cc.Invoke(ctx, GovernanceEngine_AnalyzeContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceEngineClient) ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResponse)
	err := c.cc.Invoke(ctx, GovernanceEngine_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceEngineClient) CacheGet(ctx context.Context, in *CacheKey, opts ...grpc.CallOption) (*CacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheResponse)
	err := c.cc.Invoke(ctx, GovernanceEngine_CacheGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceEngineClient) CachePut(ctx context.Context, in *CachePutRequest, opts ...grpc.CallOption) (*CacheResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheResult)
	err := c.cc.Invoke(ctx, GovernanceEngine_CachePut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceEngineClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, GovernanceEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GovernanceEngineServer is the server API for GovernanceEngine service.
// All implementations must embed UnimplementedGovernanceEngineServer
// for forward compatibility.
type GovernanceEngineServer interface {
	// Pre-inference evaluation: authenticate caller, check model attestation,
	// evaluate pre-inference policies, verify budget, sanitize PII if enabled,
	// and resolve A/B test variants.  Called before the Go proxy forwards the
	// request to the LLM provider.
	EvaluatePreInference(context.Context, *PreInferenceRequest) (*PreInferenceResult, error)
	// Post-inference evaluation: run content analyzers (PII, toxicity, Llama Guard,
	// DLP) on the model response, evaluate post-inference policies, and restore
	// PII-sanitized tokens if applicable.  Called after the Go proxy receives the
	// LLM provider response.
	EvaluatePostInference(context.Context, *PostInferenceRequest) (*PostInferenceResult, error)
	// Persist an execution record to WAL + Walacor backend (dual-write).
	// Fire-and-forget from the Go proxy side — the sidecar handles retries.
	RecordExecution(context.Context, *ExecutionRecord) (*WriteResult, error)
	// Session chain: get the next (sequence_number, previous_record_hash) for a
	// session's Merkle chain.  Called before building the execution record.
	NextChainValues(context.Context, *ChainRequest) (*ChainValues, error)
	// Session chain: commit a new link after the execution record is written.
	UpdateChain(context.Context, *ChainUpdate) (*ChainResult, error)
	// Standalone content analysis — can run in parallel with the LLM call for
	// prompt-side analysis while the provider is processing.
	AnalyzeContent(context.Context, *ContentPayload) (*AnalysisResult, error)
	// Execute a tool (MCP server tool or built-in like web_search).
	// Used when the Go proxy detects tool_calls in the LLM response and the
	// tool strategy is "active".
	ExecuteTool(context.Context, *ToolRequest) (*ToolResponse, error)
	// Semantic cache lookup — check if an equivalent prompt was recently served.
	CacheGet(context.Context, *CacheKey) (*CacheResponse, error)
	// Semantic cache store — save a response for future cache hits.
	CachePut(context.Context, *CachePutRequest) (*CacheResult, error)
	// Health check — used by Go proxy readiness probes and startup sequencing.
	HealthCheck(context.Context, *Empty) (*HealthStatus, error)
	mustEmbedUnimplementedGovernanceEngineServer()
}

// UnimplementedGovernanceEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGovernanceEngineServer struct{}

func (UnimplementedGovernanceEngineServer) EvaluatePreInference(context.Context, *PreInferenceRequest) (*PreInferenceResult, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluatePreInference not implemented")
}
func (UnimplementedGovernanceEngineServer) EvaluatePostInference(context.Context, *PostInferenceRequest) (*PostInferenceResult, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluatePostInference not implemented")
}
func (UnimplementedGovernanceEngineServer) RecordExecution(context.Context, *ExecutionRecord) (*WriteResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordExecution not implemented")
}
func (UnimplementedGovernanceEngineServer) NextChainValues(context.Context, *ChainRequest) (*ChainValues, error) {
	return nil, status.Error(codes.Unimplemented, "method NextChainValues not implemented")
}
func (UnimplementedGovernanceEngineServer) UpdateChain(context.Context, *ChainUpdate) (*ChainResult, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChain not implemented")
}
func (UnimplementedGovernanceEngineServer) AnalyzeContent(context.Context, *ContentPayload) (*AnalysisResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeContent not implemented")
}
func (UnimplementedGovernanceEngineServer) ExecuteTool(context.Context, *ToolRequest) (*ToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedGovernanceEngineServer) CacheGet(context.Context, *CacheKey) (*CacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheGet not implemented")
}
func (UnimplementedGovernanceEngineServer) CachePut(context.Context, *CachePutRequest) (*CacheResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CachePut not implemented")
}
func (UnimplementedGovernanceEngineServer) HealthCheck(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGovernanceEngineServer) mustEmbedUnimplementedGovernanceEngineServer() {}
func (UnimplementedGovernanceEngineServer) testEmbeddedByValue()                          {}

// UnsafeGovernanceEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GovernanceEngineServer will
// result in compilation errors.
type UnsafeGovernanceEngineServer interface {
	mustEmbedUnimplementedGovernanceEngineServer()
}

func RegisterGovernanceEngineServer(s grpc.ServiceRegistrar, srv GovernanceEngineServer) {
	// If the following call panics, it indicates UnimplementedGovernanceEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GovernanceEngine_ServiceDesc, srv)
}

func _GovernanceEngine_EvaluatePreInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).EvaluatePreInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_EvaluatePreInference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).EvaluatePreInference(ctx, req.(*PreInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceEngine_EvaluatePostInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).EvaluatePostInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_EvaluatePostInference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).EvaluatePostInference(ctx, req.(*PostInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceEngine_RecordExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).RecordExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_RecordExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).RecordExecution(ctx, req.(*ExecutionRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceEngine_NextChainValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).NextChainValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_NextChainValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).NextChainValues(ctx, req.(*ChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceEngine_UpdateChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).UpdateChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_UpdateChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).UpdateChain(ctx, req.(*ChainUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceEngine_AnalyzeContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).AnalyzeContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_AnalyzeContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).AnalyzeContent(ctx, req.(*ContentPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceEngine_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).ExecuteTool(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceEngine_CacheGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).CacheGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_CacheGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).CacheGet(ctx, req.(*CacheKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceEngine_CachePut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CachePutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).CachePut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_CachePut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).CachePut(ctx, req.(*CachePutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceEngineServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GovernanceEngine_ServiceDesc is the grpc.ServiceDesc for GovernanceEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GovernanceEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "walacor.governance.v1.GovernanceEngine",
	HandlerType: (*GovernanceEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluatePreInference",
			Handler:    _GovernanceEngine_EvaluatePreInference_Handler,
		},
		{
			MethodName: "EvaluatePostInference",
			Handler:    _GovernanceEngine_EvaluatePostInference_Handler,
		},
		{
			MethodName: "RecordExecution",
			Handler:    _GovernanceEngine_RecordExecution_Handler,
		},
		{
			MethodName: "NextChainValues",
			Handler:    _GovernanceEngine_NextChainValues_Handler,
		},
		{
			MethodName: "UpdateChain",
			Handler:    _GovernanceEngine_UpdateChain_Handler,
		},
		{
			MethodName: "AnalyzeContent",
			Handler:    _GovernanceEngine_AnalyzeContent_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _GovernanceEngine_ExecuteTool_Handler,
		},
		{
			MethodName: "CacheGet",
			Handler:    _GovernanceEngine_CacheGet_Handler,
		},
		{
			MethodName: "CachePut",
			Handler:    _GovernanceEngine_CachePut_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GovernanceEngine_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "governance.proto",
}
